@startuml "Visualizar Imóveis - Cliente"
hide footbox

actor Cliente as cliente
participant "Tela Principal" as tela_principal
participant "Controle de Imóveis" as controle_imoveis
participant "Imóvel" as imovel
database "Banco de Dados" as bd

== Cliente pesquisa imóveis ==

cliente -> tela_principal: pesquisarImoveis(filtros: String)
activate tela_principal

tela_principal -> controle_imoveis: obterImoveis(filtros: String)
activate controle_imoveis

controle_imoveis -> bd: consultarImoveis(filtros: String)
activate bd
bd --> controle_imoveis: List<Imovel>
deactivate bd

controle_imoveis --> tela_principal: List<Imovel>
deactivate controle_imoveis

alt Imóveis encontrados?
    tela_principal -> cliente: exibirListaImoveis(listaImoveis: List<Imovel>)
else Nenhum imóvel encontrado
    tela_principal -> cliente: exibirMensagem("Nenhum imóvel encontrado")
end

== Cliente seleciona imóvel para detalhes ==

cliente -> tela_principal: selecionarImovel(idImovel: Integer)
tela_principal -> controle_imoveis: buscarDetalhesImovel(idImovel: Integer)
activate controle_imoveis

controle_imoveis -> bd: consultarDetalhes(idImovel: Integer)
activate bd
bd --> controle_imoveis: Imovel
deactivate bd

controle_imoveis --> tela_principal: Imovel
deactivate controle_imoveis

tela_principal -> cliente: exibirDetalhesImovel(detalhesImovel: Imovel)

deactivate tela_principal

@enduml
