@startuml "Gerenciamento de Imóveis - Locador"
hide footbox

actor Locador as locador
participant TelaGerenciamentoImoveis as tela_gerenciamento_imoveis
participant ControleImovel as controle_imovel
participant ControleReserva as controle_reserva
participant Imovel as imovel
participant Reserva as reserva
database BD as bd

locador -> tela_gerenciamento_imoveis: acessarGerenciamentoImoveis()
activate tela_gerenciamento_imoveis

tela_gerenciamento_imoveis -> controle_imovel: obterListaImoveis()
activate controle_imovel

controle_imovel -> bd: consultarImoveisLocador(): String[]
activate bd
bd --> controle_imovel
deactivate bd

controle_imovel --> tela_gerenciamento_imoveis
deactivate controle_imovel

tela_gerenciamento_imoveis -> controle_imovel: adicionarImovel(dados: String)
activate controle_imovel

controle_imovel -> bd: inserirImovel(dados: String)
activate bd
bd --> controle_imovel
deactivate bd

controle_imovel -> imovel: <<create>>
activate imovel

controle_imovel --> tela_gerenciamento_imoveis
deactivate controle_imovel

tela_gerenciamento_imoveis -> controle_reserva: gerenciarReservas()
activate controle_reserva

controle_reserva -> bd: consultarReservas(): String[]
activate bd
bd --> controle_reserva
deactivate bd

controle_reserva -> reserva: atualizarStatusReserva(id_reserva: String, status: String)

controle_reserva --> tela_gerenciamento_imoveis
deactivate controle_reserva

deactivate tela_gerenciamento_imoveis
@enduml
