# Generated by Django 4.2.3 on 2025-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.CharField(max_length=320)),
                ('endereco', models.CharField(max_length=140)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
