# Generated by Django 4.2.3 on 2025-02-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='imovel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel'),
        ),
    ]
